// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC79FKtepu2FLMeZaseWeveVDhdVhNIPXE',
    appId: '1:251834196047:web:1561aeb862c705ca868a3a',
    messagingSenderId: '251834196047',
    projectId: 'qrattendance-1834c',
    authDomain: 'qrattendance-1834c.firebaseapp.com',
    storageBucket: 'qrattendance-1834c.appspot.com',
    measurementId: 'G-GEV0BD6K28',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD8d8xBNOaESu66XqnEQSXyMlVKNXrCxJA',
    appId: '1:251834196047:android:c43b26b0b15cc9ed868a3a',
    messagingSenderId: '251834196047',
    projectId: 'qrattendance-1834c',
    storageBucket: 'qrattendance-1834c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5lv0SP81gdIL0cjoAetx34wMtZU9DxMQ',
    appId: '1:251834196047:ios:221367cf641fb495868a3a',
    messagingSenderId: '251834196047',
    projectId: 'qrattendance-1834c',
    storageBucket: 'qrattendance-1834c.appspot.com',
    iosBundleId: 'com.example.kendice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5lv0SP81gdIL0cjoAetx34wMtZU9DxMQ',
    appId: '1:251834196047:ios:adc3feaecc7b76ec868a3a',
    messagingSenderId: '251834196047',
    projectId: 'qrattendance-1834c',
    storageBucket: 'qrattendance-1834c.appspot.com',
    iosBundleId: 'com.example.kendice.RunnerTests',
  );
}
